# Nombre de la aplicación
spring.application.name=demo

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/user_api
spring.datasource.username=postgres
spring.datasource.password=amesillo

# Configuración de JPA / Hibernate
# 'update' crea la tabla automáticamente si no existe
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
